// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace ApplicationParapente.DataModel.Entities
{
    public partial class LandingSite : Model
    {
        public LandingSite()
        {
            Fly = new HashSet<Fly>();
        }

        [Key]
        public int Id { get; set; }
        [StringLength(100)]
        public string Name { get; set; }
        [Column(TypeName = "text")]
        public string Orientation { get; set; }
        [StringLength(100)]
        public string Description { get; set; }
        [Column("Id_Level")]
        public int IdLevel { get; set; }

        [ForeignKey(nameof(IdLevel))]
        [InverseProperty(nameof(Level.LandingSite))]
        public virtual Level IdLevelNavigation { get; set; }
        [InverseProperty("IdLandingSiteNavigation")]
        public virtual ICollection<Fly> Fly { get; set; }
    }
}